In [10]:
import numpy as np
import os,sys

sys.path.append('.')
sys.path.append('../Mars3dof_env')
sys.path.append('../RL_lib/Utils')
%load_ext autoreload
%autoreload 2
%matplotlib nbagg
import os
print(os.getcwd())

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
/Users/briangaudet/Study/Subjects/MachineLearning/Projects/PCM/PCM_v2/Mars_DTM


In [7]:
%%html
<style>
.output_wrapper, .output {
    height:auto !important;
    max-height:1000px;  /* your desired max-height here */
}
.output_scroll {
    box-shadow:none !important;
    webkit-box-shadow:none !important;
}
</style>

In [8]:
dtm = np.load('synth_elevations.npy')
print(np.min(dtm), np.max(dtm))

0.0 382.8380000000001


In [17]:
from dtm_measurement_model import DTM_measurement_model
from altimeter_v import Altimeter
from time import time


print(dtm.shape)
print('Elevations: ',np.min(dtm),np.max(dtm))
max_bounds =  np.asarray([dtm.shape[0],dtm.shape[1]])
mm = DTM_measurement_model(dtm, print_missing_beams=True)
target_position = np.asarray([4000.,4000.,350.])

altimeter = Altimeter(mm, target_position)

pos = np.asarray([1500., 1000., 2300.])
vel = np.asarray([-30,30,-70])

alt, cvs = altimeter.get_reading(pos,vel)
print(alt,cvs)

(10500, 8000)
Elevations:  0.0 382.8380000000001
DTM MM: nref fixed:  384 10500 8000
[2551.15779697 3253.25733498 3349.4500726  2624.86264487] [-71.75136403 -80.02219773 -76.28620506 -68.01537135]


In [65]:
foo = np.random.rand(10)
print(foo)
print(np.argsort(foo))

[0.84376428 0.65565707 0.06028347 0.79938979 0.97086282 0.49355905
 0.45895305 0.48560347 0.39781786 0.92598239]
[2 8 6 7 5 1 3 0 9 4]


In [47]:
from time import time
dvec = 1.0*np.asarray([0,0,-1])
pos = np.asarray([7000,3000,1000])
t0=time()
reading, loc = mm.get_altimeter_reading(dvec,pos)
t1 = time()
print('et: ',t1-t0)
print(reading)
print(dtm[int(loc[0]),int(loc[1])])

et:  0.002228975296020508
848.0
151.72000000000003


In [140]:
pos

array([9000., 1500.,  992.])

In [22]:
foo = 20*np.random.rand(100)-10
if np.any(foo >= 10) or np.any(foo < 0):
    print('foo')

foo


In [23]:
np.cos(4*np.pi/5)

-0.8090169943749473

In [40]:
import attitude_utils as attu
ap = attu.Quaternion_attitude()
e1 = np.random.uniform(low=[-np.pi,-np.pi/2+np.pi/16,-np.pi],high=[np.pi,np.pi/2-np.pi/16,np.pi])
print(e1)
C = attu.Euler3212DCM(e1)
q1 = attu.DCM2EP(C)
q2 = ap.euler3212q(e1)
print(q1,q2)



[ 2.6215856  -0.72792281  2.92294818]
[ 0.31574881 -0.27634275 -0.88770874 -0.18950085] [-0.31574881  0.27634275  0.88770874  0.18950085]


In [47]:
for i in range(10000):
    e1 = np.random.uniform(low=[-np.pi,-np.pi/2+np.pi/16,-np.pi],high=[np.pi,np.pi/2-np.pi/16,np.pi])
    C = attu.Euler3212DCM(e1)
    q1 = attu.DCM2EP(C)
    q2 = ap.euler3212q(e1)
    assert q1[0] > 0

In [43]:
for i in range(10000):
    q1 = np.random.uniform(low=-1,high=1,size=4)
    q1 /= np.linalg.norm(q1)
    C = attu.EP2DCM(q1)
    e1 = attu.DCM2Euler321(C)
    e2 = ap.q2Euler321(q1)
    delta = np.linalg.norm(e1-e2)
    if delta > 1e-6:
        print(e1,e2)
    


In [44]:
for i in range(10000):
    q1 = np.random.uniform(low=-1,high=1,size=4)
    q1 /= np.linalg.norm(q1)
    q2 = -q1
    e1 = ap.q2Euler321(q1)
    e2 = ap.q2Euler321(q2)
    delta = np.linalg.norm(e1-e2)
    if delta > 1e-6:
        print(e1,e2)
        

In [83]:
bob = 100*np.random.rand(10,2)
lim = np.asarray([10,20])
foo = np.any(bob >= lim,axis=1)
print(foo)


[ True  True  True  True  True  True  True  True  True  True]


In [96]:
bob = 100*np.random.rand(10,2)
print(bob)
lim = np.asarray([10,40])
idx = np.all(bob < lim,axis=1)
print(idx)
print(bob[idx])

[[56.93647801 39.38629065]
 [12.62343411 60.70616358]
 [79.13006674 88.17707453]
 [ 5.29155567 35.88039749]
 [ 8.69369551 20.04196537]
 [96.08842764 70.30427356]
 [91.31300504  1.40609393]
 [49.93390444 93.18367898]
 [95.6773103   9.64294144]
 [ 2.3369721  25.5418935 ]]
[False False False  True  True False False False False  True]
[[ 5.29155567 35.88039749]
 [ 8.69369551 20.04196537]
 [ 2.3369721  25.5418935 ]]


In [102]:
b1 = np.asarray([True,False,False,True])
b2 = np.asarray([False,True,True,True])
print(np.bitwise_and(b1,b2))

[False False False  True]
